# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20191011_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'images/'),
            preserve_default=False,
        ),
    ]
