# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_name',
            new_name='location_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(blank=True, db_column=b'category_name', on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(blank=True, db_column=b'location_name', on_delete=django.db.models.deletion.CASCADE, to='photos.Location'),
        ),
    ]
